import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { cn } from "@/lib/utils";
import { Menu } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";

const links = [{ href: "/directorio", label: "Buscar atención" }, { href: "/pregunta-al-experto", label: "Pregunta al experto" }, { href: "/profesionales", label: "Para profesionales" }, { href: "/asistente", label: "Ayuda" }];
export function DucktorsHeader() { const [open, setOpen] = useState(false); const [location] = useLocation(); return <header className="sticky top-0 z-50 border-b border-sky-100 bg-white/90 backdrop-blur-xl"><div className="container flex h-[72px] items-center justify-between gap-6"><Link href="/" className="flex items-center gap-2.5 text-cobalt-800" aria-label="Ducktors, inicio"><span className="grid size-11 shrink-0 place-items-center overflow-hidden rounded-2xl border border-sky-100 bg-white shadow-[0_8px_20px_rgba(34,92,197,.18)]"><img src="/manus-storage/ducktors-logo_08547fd7.jpg" alt="Logo Ducktor" className="size-full object-cover" /></span><span className="font-display text-[1.4rem] font-bold tracking-[-.055em]">Ducktors</span></Link><nav className="hidden items-center gap-6 lg:flex" aria-label="Navegación principal">{links.map(link => <Link key={link.href} href={link.href} className={cn("text-sm font-semibold transition-colors hover:text-cobalt-700", location === link.href ? "text-cobalt-700" : "text-slate-600")}>{link.label}</Link>)}</nav><div className="hidden items-center gap-3 sm:flex"><Button variant="ghost" className="font-semibold text-slate-700" onClick={() => startLogin()}>Iniciar sesión</Button><Link href="/directorio"><Button className="bg-cobalt-700 font-semibold hover:bg-cobalt-800">Encontrar profesional</Button></Link></div><button className="grid size-10 place-items-center rounded-xl text-cobalt-800 hover:bg-sky-50 lg:hidden" aria-label="Abrir navegación" onClick={() => setOpen(!open)}><Menu className="size-5" /></button></div>{open && <nav className="border-t border-sky-100 bg-white p-4 lg:hidden"><div className="container grid gap-2">{links.map(link => <Link key={link.href} href={link.href} onClick={() => setOpen(false)} className="rounded-xl px-4 py-3 font-semibold text-slate-700 hover:bg-sky-50">{link.label}</Link>)}</div></nav>}</header>; }
