import { index, int, mysqlEnum, mysqlTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export const professionalProfiles = mysqlTable("professional_profiles", {
  id: int("id").autoincrement().primaryKey(), source: mysqlEnum("source", ["yellow_duxn"]).default("yellow_duxn").notNull(), sourceRecordId: varchar("sourceRecordId", { length: 128 }).notNull(), ownerUserId: int("ownerUserId").references(() => users.id, { onDelete: "set null" }), slug: varchar("slug", { length: 180 }).notNull(), displayName: varchar("displayName", { length: 255 }).notNull(), profileType: mysqlEnum("profileType", ["medico", "dentista", "psicologo", "clinica"]).notNull(), specialties: text("specialties").notNull(), city: varchar("city", { length: 160 }).notNull(), locality: varchar("locality", { length: 160 }), contactEmail: varchar("contactEmail", { length: 320 }), insuranceText: text("insuranceText"), symptomsText: text("symptomsText"), biography: text("biography"), photoUrl: text("photoUrl"), telemedicineEnabled: int("telemedicineEnabled").default(0).notNull(), inPersonEnabled: int("inPersonEnabled").default(1).notNull(), profileStatus: mysqlEnum("profileStatus", ["pending", "published", "suspended"]).default("pending").notNull(), verificationStatus: mysqlEnum("verificationStatus", ["pending", "verified", "rejected"]).default("pending").notNull(), searchTitle: varchar("searchTitle", { length: 180 }), searchDescription: text("searchDescription"), catalogSyncedAt: timestamp("catalogSyncedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("professional_source_record_unq").on(table.source, table.sourceRecordId), uniqueIndex("professional_slug_unq").on(table.slug), index("professional_public_directory_idx").on(table.profileStatus, table.verificationStatus, table.city)]);

export const availabilitySlots = mysqlTable("availability_slots", {
  id: int("id").autoincrement().primaryKey(), professionalId: int("professionalId").notNull().references(() => professionalProfiles.id, { onDelete: "cascade" }), sourceSlotId: varchar("sourceSlotId", { length: 160 }), startsAt: timestamp("startsAt").notNull(), endsAt: timestamp("endsAt").notNull(), modality: mysqlEnum("modality", ["presencial", "videollamada"]).notNull(), state: mysqlEnum("state", ["available", "reserved", "blocked"]).default("available").notNull(), catalogSyncedAt: timestamp("catalogSyncedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => [uniqueIndex("availability_source_slot_unq").on(table.professionalId, table.sourceSlotId), index("availability_professional_time_idx").on(table.professionalId, table.startsAt, table.state)]);

export const appointments = mysqlTable("appointments", {
  id: int("id").autoincrement().primaryKey(), patientUserId: int("patientUserId").notNull().references(() => users.id, { onDelete: "restrict" }), professionalId: int("professionalId").notNull().references(() => professionalProfiles.id, { onDelete: "restrict" }), availabilitySlotId: int("availabilitySlotId").references(() => availabilitySlots.id, { onDelete: "set null" }), modality: mysqlEnum("modality", ["presencial", "videollamada"]).notNull(), state: mysqlEnum("state", ["requested", "confirmed", "cancelled", "completed", "no_show"]).default("requested").notNull(), startsAt: timestamp("startsAt").notNull(), endsAt: timestamp("endsAt").notNull(), patientNote: text("patientNote"), telemedicineRoomUrl: text("telemedicineRoomUrl"), confirmedAt: timestamp("confirmedAt"), patientReminderSentAt: timestamp("patientReminderSentAt"), professionalReminderSentAt: timestamp("professionalReminderSentAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [index("appointment_patient_time_idx").on(table.patientUserId, table.startsAt), index("appointment_professional_time_idx").on(table.professionalId, table.startsAt)]);

export const notificationDeliveries = mysqlTable("notification_deliveries", {
  id: int("id").autoincrement().primaryKey(), appointmentId: int("appointmentId").notNull().references(() => appointments.id, { onDelete: "cascade" }), recipientRole: mysqlEnum("recipientRole", ["patient", "professional"]).notNull(), recipientEmail: varchar("recipientEmail", { length: 320 }).notNull(), kind: mysqlEnum("kind", ["confirmation", "reminder"]).notNull(), state: mysqlEnum("state", ["queued", "sent", "failed"]).default("queued").notNull(), scheduledAt: timestamp("scheduledAt").notNull(), sentAt: timestamp("sentAt"), providerMessageId: varchar("providerMessageId", { length: 255 }), lastError: text("lastError"), attempts: int("attempts").default(0).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("notification_delivery_idempotency_unq").on(table.appointmentId, table.recipientRole, table.kind), index("notification_delivery_due_idx").on(table.state, table.scheduledAt)]);

export const automationJobs = mysqlTable("automation_jobs", {
  id: int("id").autoincrement().primaryKey(), jobKey: varchar("jobKey", { length: 100 }).notNull(), taskUid: varchar("taskUid", { length: 65 }).notNull(), cron: varchar("cron", { length: 80 }).notNull(), enabled: int("enabled").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [uniqueIndex("automation_job_key_unq").on(table.jobKey), uniqueIndex("automation_task_uid_unq").on(table.taskUid)]);

export const reviews = mysqlTable("reviews", {
  id: int("id").autoincrement().primaryKey(), appointmentId: int("appointmentId").notNull().references(() => appointments.id, { onDelete: "restrict" }), patientUserId: int("patientUserId").notNull().references(() => users.id, { onDelete: "restrict" }), professionalId: int("professionalId").notNull().references(() => professionalProfiles.id, { onDelete: "restrict" }), rating: int("rating").notNull(), body: text("body"), state: mysqlEnum("state", ["pending", "published", "rejected"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), publishedAt: timestamp("publishedAt"),
}, table => [uniqueIndex("review_one_per_appointment_unq").on(table.appointmentId), index("review_professional_state_idx").on(table.professionalId, table.state)]);

export const expertQuestions = mysqlTable("expert_questions", {
  id: int("id").autoincrement().primaryKey(), topic: varchar("topic", { length: 180 }).notNull(), body: text("body").notNull(), state: mysqlEnum("state", ["pending", "answered", "hidden"]).default("pending").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [index("expert_question_state_created_idx").on(table.state, table.createdAt)]);

export const expertAnswers = mysqlTable("expert_answers", {
  id: int("id").autoincrement().primaryKey(), questionId: int("questionId").notNull().references(() => expertQuestions.id, { onDelete: "cascade" }), professionalId: int("professionalId").notNull().references(() => professionalProfiles.id, { onDelete: "restrict" }), body: text("body").notNull(), state: mysqlEnum("state", ["pending", "published", "hidden"]).default("pending").notNull(), publishedAt: timestamp("publishedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(),
}, table => [index("expert_answer_question_state_idx").on(table.questionId, table.state)]);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
