import { and, eq, inArray, notInArray } from "drizzle-orm";
import { availabilitySlots, professionalProfiles } from "../drizzle/schema";
import { getDb } from "./db";
import { fetchYellowDuxnCatalog, type YellowDuxnCatalogPayload } from "./yellowDuxn";

const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export function staleSlotReconciliation(sourceSlotIds: string[]) { return sourceSlotIds.length ? "except-synced" as const : "all" as const; }
export async function persistYellowDuxnCatalog(payload: YellowDuxnCatalogPayload) { const db = await getDb(); if (!db) throw new Error("La base de datos no está disponible."); const syncedAt = new Date(); await db.transaction(async tx => { for (const provider of payload.professionals) { await tx.insert(professionalProfiles).values({ source: "yellow_duxn", sourceRecordId: provider.id, slug: `${slugify(provider.name)}-${slugify(provider.id)}`.slice(0, 180), displayName: provider.name, profileType: provider.type, specialties: provider.specialties.join(", "), city: provider.city, locality: provider.locality || null, contactEmail: provider.contactEmail || null, insuranceText: provider.insurances?.join(", ") || null, symptomsText: provider.symptoms?.join(", ") || null, biography: provider.biography || null, photoUrl: provider.photoUrl || null, telemedicineEnabled: provider.telemedicineEnabled ? 1 : 0, inPersonEnabled: provider.inPersonEnabled === false ? 0 : 1, profileStatus: provider.status || "published", verificationStatus: provider.verified ? "verified" : "pending", catalogSyncedAt: syncedAt }).onDuplicateKeyUpdate({ set: { displayName: provider.name, specialties: provider.specialties.join(", "), city: provider.city, locality: provider.locality || null, contactEmail: provider.contactEmail || null, insuranceText: provider.insurances?.join(", ") || null, symptomsText: provider.symptoms?.join(", ") || null, biography: provider.biography || null, photoUrl: provider.photoUrl || null, telemedicineEnabled: provider.telemedicineEnabled ? 1 : 0, inPersonEnabled: provider.inPersonEnabled === false ? 0 : 1, profileStatus: provider.status || "published", verificationStatus: provider.verified ? "verified" : "pending", catalogSyncedAt: syncedAt } }); }
    const profiles = await tx.select({ id: professionalProfiles.id, sourceRecordId: professionalProfiles.sourceRecordId }).from(professionalProfiles).where(eq(professionalProfiles.source, "yellow_duxn")); const profileBySource = new Map(profiles.map(profile => [profile.sourceRecordId, profile.id])); const syncedProfessionalIds = payload.professionals.map(provider => profileBySource.get(provider.id)).filter((value): value is number => Boolean(value)); for (const slot of payload.slots) { const professionalId = profileBySource.get(slot.professionalId); if (!professionalId) continue; await tx.insert(availabilitySlots).values({ professionalId, sourceSlotId: slot.id, startsAt: new Date(slot.startsAt), endsAt: new Date(slot.endsAt), modality: slot.modality, state: slot.state, catalogSyncedAt: syncedAt }).onDuplicateKeyUpdate({ set: { startsAt: new Date(slot.startsAt), endsAt: new Date(slot.endsAt), modality: slot.modality, state: slot.state, catalogSyncedAt: syncedAt } }); }
    const sourceSlotIds = payload.slots.map(slot => slot.id); if (syncedProfessionalIds.length) { const reconciliation = staleSlotReconciliation(sourceSlotIds); const staleSlots = tx.update(availabilitySlots).set({ state: "blocked", catalogSyncedAt: syncedAt }); if (reconciliation === "all") await staleSlots.where(inArray(availabilitySlots.professionalId, syncedProfessionalIds)); else await staleSlots.where(and(inArray(availabilitySlots.professionalId, syncedProfessionalIds), notInArray(availabilitySlots.sourceSlotId, sourceSlotIds))); }
  }); return { professionalCount: payload.professionals.length, slotCount: payload.slots.length, syncedAt }; }
export async function syncYellowDuxnCatalog() { return persistYellowDuxnCatalog(await fetchYellowDuxnCatalog()); }
