import { and, desc, eq, isNull } from "drizzle-orm";
import { appointments, expertAnswers, expertQuestions, professionalProfiles, reviews } from "../drizzle/schema";
import { getDb } from "./db";
import { type DirectoryFilters, providerMatchesFilters } from "./healthCatalog";
export async function listPublishedDirectory(filters: DirectoryFilters) { const db = await getDb(); if (!db) return []; const providers = await db.select().from(professionalProfiles).where(and(eq(professionalProfiles.source, "yellow_duxn"), eq(professionalProfiles.profileStatus, "published"))); return providers.filter(provider => providerMatchesFilters(provider, filters)); }
export async function getPublicProfessionalBySlug(slug: string) { const db = await getDb(); if (!db) return null; const [provider] = await db.select().from(professionalProfiles).where(and(eq(professionalProfiles.slug, slug), eq(professionalProfiles.profileStatus, "published"))).limit(1); return provider ?? null; }
export async function createAnonymousQuestion(input: { topic: string; body: string }) { const db = await getDb(); if (!db) throw new Error("La base de datos no está disponible."); await db.insert(expertQuestions).values({ topic: input.topic.trim(), body: input.body.trim() }); }
export async function listPublishedQuestions() { const db = await getDb(); if (!db) return []; return db.select({ id: expertQuestions.id, topic: expertQuestions.topic, question: expertQuestions.body, createdAt: expertQuestions.createdAt, answer: expertAnswers.body, answeredAt: expertAnswers.publishedAt, professionalName: professionalProfiles.displayName, verificationStatus: professionalProfiles.verificationStatus }).from(expertQuestions).innerJoin(expertAnswers, and(eq(expertAnswers.questionId, expertQuestions.id), eq(expertAnswers.state, "published"))).innerJoin(professionalProfiles, and(eq(professionalProfiles.id, expertAnswers.professionalId), eq(professionalProfiles.verificationStatus, "verified"))).where(eq(expertQuestions.state, "answered")).orderBy(desc(expertQuestions.createdAt)).limit(20); }
export async function listPublishedReviewsBySlug(slug: string) { const db = await getDb(); if (!db) return []; return db.select({ id: reviews.id, rating: reviews.rating, body: reviews.body, createdAt: reviews.createdAt }).from(reviews).innerJoin(professionalProfiles, eq(professionalProfiles.id, reviews.professionalId)).where(and(eq(professionalProfiles.slug, slug), eq(reviews.state, "published"))).orderBy(desc(reviews.publishedAt)).limit(30); }
export async function createPatientReview(input: { patientUserId: number; appointmentId: number; rating: number; body?: string }) { const db = await getDb(); if (!db) throw new Error("La base de datos no está disponible."); const [appointment] = await db.select().from(appointments).where(eq(appointments.id, input.appointmentId)).limit(1); if (!appointment) return { allowed: false, reason: "No se encontró la cita indicada." }; const [existingReview] = await db.select({ id: reviews.id }).from(reviews).where(eq(reviews.appointmentId, input.appointmentId)).limit(1); const { canSubmitReview } = await import("./reviewPolicy"); const eligibility = canSubmitReview({ appointmentState: appointment.state, isAppointmentOwner: appointment.patientUserId === input.patientUserId, alreadyReviewed: Boolean(existingReview) }); if (!eligibility.allowed) return eligibility; await db.insert(reviews).values({ appointmentId: appointment.id, patientUserId: input.patientUserId, professionalId: appointment.professionalId, rating: input.rating, body: input.body?.trim() || null, state: "pending" }); return { allowed: true, reason: "Tu opinión fue recibida y será revisada antes de publicarse." }; }
export async function listEligibleReviewAppointments(patientUserId: number, professionalId: number) { const db = await getDb(); if (!db) return []; return db.select({ appointmentId: appointments.id, startsAt: appointments.startsAt }).from(appointments).leftJoin(reviews, eq(reviews.appointmentId, appointments.id)).where(and(eq(appointments.patientUserId, patientUserId), eq(appointments.professionalId, professionalId), eq(appointments.state, "completed"), isNull(reviews.id))).orderBy(desc(appointments.startsAt)); }
export async function updateOwnedProfessionalProfile(userId: number, input: { displayName?: string; biography?: string; searchTitle?: string; searchDescription?: string }) { const db = await getDb(); if (!db) throw new Error("La base de datos no está disponible."); const [profile] = await db.select({ id: professionalProfiles.id }).from(professionalProfiles).where(eq(professionalProfiles.ownerUserId, userId)).limit(1); if (!profile) throw new Error("Aún no existe un perfil Yellow Duxn vinculado a esta cuenta."); await db.update(professionalProfiles).set({ displayName: input.displayName, biography: input.biography, searchTitle: input.searchTitle, searchDescription: input.searchDescription }).where(eq(professionalProfiles.id, profile.id)); return { updated: true }; }
export async function linkProfessionalProfile(userId: number, email: string | null, sourceRecordId: string) { if (!email) throw new Error("La cuenta debe tener un correo electrónico para vincular un perfil."); const db = await getDb(); if (!db) throw new Error("La base de datos no está disponible."); const [profile] = await db.select().from(professionalProfiles).where(and(eq(professionalProfiles.sourceRecordId, sourceRecordId), eq(professionalProfiles.contactEmail, email))).limit(1); if (!profile) throw new Error("No existe un perfil autorizado para este correo."); await db.update(professionalProfiles).set({ ownerUserId: userId }).where(eq(professionalProfiles.id, profile.id)); return { linked: true, slug: profile.slug }; }
