export type YellowDuxnProfessional = {
  id: string; name: string; type: "medico" | "dentista" | "psicologo" | "clinica"; specialties: string[]; city: string; locality?: string; contactEmail?: string; insurances?: string[]; symptoms?: string[]; biography?: string; photoUrl?: string; telemedicineEnabled?: boolean; inPersonEnabled?: boolean; verified?: boolean; status?: "published" | "pending" | "suspended";
};
export type YellowDuxnSlot = { id: string; professionalId: string; startsAt: string; endsAt: string; modality: "presencial" | "videollamada"; state: "available" | "reserved" | "blocked" };
export type YellowDuxnCatalogPayload = { professionals: YellowDuxnProfessional[]; slots: YellowDuxnSlot[] };
type FetchLike = typeof fetch;

export function yellowDuxnConfig() { const baseUrl = process.env.YELLOW_DUXN_CATALOG_BASE_URL; const apiKey = process.env.YELLOW_DUXN_CATALOG_API_KEY; const path = process.env.YELLOW_DUXN_CATALOG_PATH; const authHeader = process.env.YELLOW_DUXN_AUTH_HEADER || "Authorization"; const authScheme = process.env.YELLOW_DUXN_AUTH_SCHEME || "Bearer"; return { baseUrl, apiKey, path, authHeader, authScheme, configured: Boolean(baseUrl && apiKey && path) }; }
export function yellowDuxnUrl(baseUrl: string, path: string) { return new URL(path, baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`).toString(); }
export function asCatalogPayload(payload: unknown): YellowDuxnCatalogPayload { if (!payload || typeof payload !== "object") throw new Error("Yellow Duxn devolvió una respuesta de catálogo no válida."); const record = payload as Record<string, unknown>; const professionals = record.professionals; const slots = record.slots; if (!Array.isArray(professionals) || !Array.isArray(slots)) throw new Error("Yellow Duxn debe devolver los arreglos 'professionals' y 'slots'."); return { professionals: professionals as YellowDuxnProfessional[], slots: slots as YellowDuxnSlot[] }; }
export function validateCatalog(payload: YellowDuxnCatalogPayload) { const professionalIds = new Set<string>(); for (const provider of payload.professionals) { if (!provider.id || !provider.name || !provider.type || !provider.city || !Array.isArray(provider.specialties) || provider.specialties.length === 0) throw new Error("Yellow Duxn contiene un profesional sin los campos requeridos."); professionalIds.add(provider.id); } for (const slot of payload.slots) { if (!slot.id || !professionalIds.has(slot.professionalId) || !["presencial", "videollamada"].includes(slot.modality) || !["available", "reserved", "blocked"].includes(slot.state) || Number.isNaN(new Date(slot.startsAt).getTime()) || Number.isNaN(new Date(slot.endsAt).getTime())) throw new Error("Yellow Duxn contiene una disponibilidad no válida."); } return payload; }
export async function fetchYellowDuxnCatalog(fetcher: FetchLike = fetch) { const config = yellowDuxnConfig(); if (!config.configured || !config.baseUrl || !config.path || !config.apiKey) throw new Error("Yellow Duxn no está configurado. Añade URL, ruta de catálogo y credencial autorizada."); const authorization = config.authScheme ? `${config.authScheme} ${config.apiKey}` : config.apiKey; const response = await fetcher(yellowDuxnUrl(config.baseUrl, config.path), { headers: { Accept: "application/json", [config.authHeader]: authorization } }); if (!response.ok) throw new Error(`Yellow Duxn respondió ${response.status}.`); return validateCatalog(asCatalogPayload(await response.json())); }
